FROM debian:10

USER root
WORKDIR /home/app

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl unzip \
    && apt-get -y autoclean

